---
- name: Installation de Docker sur les serveurs AWS
  hosts: all
  become: yes

  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer les dépendances Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Installer Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Activer et démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes
